### ISSUE TITLE
version 8 vs version 9

### ISSUE THREAD

**Issue by nitin16** [LitleCo/litle-sdk-for-dotNet#46]
Hi, 

Currently our merchant account is set to use version 8 of XML. WE are converting our legacy code to use .net SDK. Vantiv notified us that if we move to version 9 or 11 we will need to do re certification all processes which might cause delays in our deadline.  

My question is, how up-to date release for xml 8 sdk ? or would you recommend upgrading to sdk 9 or 11 and go through certification process?

Thanks, 
Nitin

**Comment by brianarnold789** [comment]
Hi @nitin16,

Great question, the versioning scheme we use in the SDK matches the XML version implemented underneath. So, SDK v8.x uses XML v8.x. If you are looking to keep the same payment functionality staying on v8.x is the way to go. All versions of the SDK receive the applicable bug fixes, so that shouldn't be a concern (the latest v8 release is 8.29.4 and is a bugfix).

If, however, you are looking to leverage a feature present in either XML v9.x or v11.x you would need to upgrade the SDK. This upgrade could be completed fairly easily after moving to v8.x as most of the basic implementations don't change version to version.

If you need a more detailed explanation or run into any issues with the SDK please contact sdksupport@vantiv.com

Thanks,
Brian

**Comment by nitin16** [comment]
This helps. Thanks for quick response.
